<?php

declare(strict_types=1);

namespace App\Service\Storage;

use Psr\Log\LoggerInterface;
use Symfony\Contracts\HttpClient\Exception\TransportExceptionInterface;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;

final class SupabaseStorageService
{
    public function __construct(
        private readonly HttpClientInterface $httpClient,
        private readonly LoggerInterface $logger,
        private readonly string $supabaseUrl,
        private readonly string $supabaseSecretKey,
        private readonly string $supabaseBucket,
    ) {
    }

    /**
     * Uploads one file to Supabase Storage and returns the storage object path.
     *
     * @throws \RuntimeException
     */
    public function uploadJobApplicationFile(UploadedFile $file, string $folder): string
    {
        return $this->uploadFile($file, $folder);
    }

    /**
     * Upload a job application file using offer and student ids to build exact path.
     * Returns the object path (not prefixed).
     */
    public function uploadJobApplicationFileWithIds(UploadedFile $file, ?int $offerId, ?int $studentId): string
    {
        $original = $file->getClientOriginalName() ?: 'file';
        $sanitized = $this->sanitizeFilename($original);
        $uuidFile = $this->generateUuidV4();

        if ($offerId !== null && $studentId !== null) {
            $folder = sprintf('job-applications/offer-%d/student-%d', $offerId, $studentId);
        } else {
            $folder = 'job-applications/unknown-offer/unknown-student';
        }

        $objectPath = trim($folder, '/') . '/' . $uuidFile . '_' . $sanitized;

        return $this->uploadContent($objectPath, fopen($file->getPathname(), 'rb'), $file->getMimeType() ?: 'application/octet-stream');
    }

    /**
     * Uploads one uploaded file to Supabase Storage and returns the storage object path.
     */
    public function uploadFile(UploadedFile $file, string $folder): string
    {
        $extension = $file->guessExtension() ?: $file->getClientOriginalExtension() ?: 'bin';
        $safeExtension = strtolower(preg_replace('/[^a-zA-Z0-9]/', '', (string) $extension) ?: 'bin');
        $objectPath = trim($folder, '/') . '/' . bin2hex(random_bytes(16)) . '.' . $safeExtension;

        return $this->uploadContent(
            $objectPath,
            fopen($file->getPathname(), 'rb'),
            $file->getMimeType() ?: 'application/octet-stream'
        );
    }

    /**
     * Uploads bytes generated by the app and returns the storage object path.
     */
    public function uploadBytes(string $content, string $folder, string $fileName, string $mimeType): string
    {
        $extension = pathinfo($fileName, PATHINFO_EXTENSION) ?: 'bin';
        $safeExtension = strtolower(preg_replace('/[^a-zA-Z0-9]/', '', (string) $extension) ?: 'bin');
        $objectPath = trim($folder, '/') . '/' . bin2hex(random_bytes(16)) . '.' . $safeExtension;

        return $this->uploadContent($objectPath, $content, $mimeType);
    }

    /**
     * Upload to an explicit object path (useful when controller builds exact path).
     * Returns the object path (not prefixed).
     */
    public function uploadToObjectPath(UploadedFile $file, string $objectPath): string
    {
        return $this->uploadContent($objectPath, fopen($file->getPathname(), 'rb'), $file->getMimeType() ?: 'application/octet-stream');
    }

    /**
     * Upload LMS content and return metadata including objectPath, mimeType and size.
     * objectPath follows: lms-content/content/{uuidFolder}/{uuidFile}_{sanitizedOriginalFileName}
     * Returns array{objectPath:string, mimeType:string, fileSize:int, fileName:string}
     */
    public function uploadLmsContent(UploadedFile $file): array
    {
        $original = $file->getClientOriginalName() ?: 'file';
        $sanitized = $this->sanitizeFilename($original);
        $uuidFolder = $this->generateUuidV4();
        $uuidFile = $this->generateUuidV4();

        $objectPath = sprintf('lms-content/content/%s/%s_%s', $uuidFolder, $uuidFile, $sanitized);

        $this->uploadContent($objectPath, fopen($file->getPathname(), 'rb'), $file->getMimeType() ?: 'application/octet-stream');

        return [
            'objectPath' => $objectPath,
            'mimeType' => $file->getMimeType() ?: 'application/octet-stream',
            'fileSize' => $file->getSize() ?? 0,
            'fileName' => $file->getClientOriginalName() ?: basename($file->getPathname()),
        ];
    }

    private function uploadContent(string $objectPath, mixed $body, string $mimeType): string
    {
        $url = rtrim($this->supabaseUrl, '/')
            . '/storage/v1/object/'
            . rawurlencode($this->supabaseBucket)
            . '/'
            . $this->encodePath($objectPath);

        try {
            $response = $this->httpClient->request('POST', $url, [
                'headers' => [
                    'Authorization' => 'Bearer ' . $this->supabaseSecretKey,
                    'apikey' => $this->supabaseSecretKey,
                    'Content-Type' => $mimeType,
                    'x-upsert' => 'false',
                ],
                'body' => $body,
            ]);

            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode >= 300) {
                throw new \RuntimeException('Supabase upload failed with status ' . $statusCode . '.');
            }

            return $objectPath;
        } catch (TransportExceptionInterface|\RuntimeException $e) {
            $this->logger->error('Supabase upload failed', [
                'objectPath' => $objectPath,
                'error' => $e->getMessage(),
            ]);

            throw new \RuntimeException('Failed to upload file to remote storage.');
        }
    }

    public function getPublicObjectUrl(string $objectPath): string
    {
        return rtrim($this->supabaseUrl, '/')
            . '/storage/v1/object/public/'
            . rawurlencode($this->supabaseBucket)
            . '/'
            . $this->encodePath($objectPath);
    }

    /**
     * @return array{content: string, mimeType: string, fileName: string}
     */
    public function downloadJobApplicationFile(string $storedReference): array
    {
        return $this->downloadStoredFile($storedReference);
    }

    /**
     * @return array{content: string, mimeType: string, fileName: string}
     */
    public function downloadStoredFile(string $storedReference): array
    {
        $trimmedReference = trim($storedReference);

        if (str_starts_with($trimmedReference, 'supabase:')) {
            $objectPath = trim(substr($trimmedReference, strlen('supabase:')));
            if ($objectPath === '') {
                throw new \RuntimeException('Invalid Supabase object path.');
            }

            return $this->downloadByObjectPath($objectPath);
        }

        if (filter_var($trimmedReference, FILTER_VALIDATE_URL)) {
            try {
                return $this->downloadFromUrl($trimmedReference, false);
            } catch (\RuntimeException $e) {
                $objectPath = $this->extractObjectPathFromPublicUrl($trimmedReference);
                if ($objectPath === null) {
                    throw $e;
                }

                return $this->downloadByObjectPath($objectPath);
            }
        }

        return $this->downloadByObjectPath($trimmedReference);
    }

    private function encodePath(string $path): string
    {
        return str_replace('%2F', '/', rawurlencode(ltrim($path, '/')));
    }

    private function sanitizeFilename(string $name): string
    {
        // Replace any character not matching [a-zA-Z0-9._-] with '_'
        $base = pathinfo($name, PATHINFO_BASENAME);
        return preg_replace('/[^a-zA-Z0-9._-]/', '_', $base) ?: '_';
    }

    private function generateUuidV4(): string
    {
        $data = random_bytes(16);
        $data[6] = chr((ord($data[6]) & 0x0f) | 0x40);
        $data[8] = chr((ord($data[8]) & 0x3f) | 0x80);
        return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
    }

    /**
     * @return array{content: string, mimeType: string, fileName: string}
     */
    private function downloadByObjectPath(string $objectPath): array
    {
        $path = ltrim($objectPath, '/');
        $url = rtrim($this->supabaseUrl, '/')
            . '/storage/v1/object/'
            . rawurlencode($this->supabaseBucket)
            . '/'
            . $this->encodePath($path);

        return $this->downloadFromUrl($url, true, basename($path));
    }

    /**
     * @return array{content: string, mimeType: string, fileName: string}
     */
    private function downloadFromUrl(string $url, bool $authenticated, ?string $fallbackFileName = null): array
    {
        $headers = [];
        if ($authenticated) {
            $headers = [
                'Authorization' => 'Bearer ' . $this->supabaseSecretKey,
                'apikey' => $this->supabaseSecretKey,
            ];
        }

        try {
            $response = $this->httpClient->request('GET', $url, ['headers' => $headers]);
            $statusCode = $response->getStatusCode();
            if ($statusCode < 200 || $statusCode >= 300) {
                throw new \RuntimeException('Supabase download failed with status ' . $statusCode . '.');
            }

            $responseHeaders = $response->getHeaders(false);
            $contentType = $responseHeaders['content-type'][0] ?? 'application/octet-stream';
            $mimeType = explode(';', $contentType)[0];

            $fileName = $fallbackFileName ?? basename((string) parse_url($url, PHP_URL_PATH));
            if ($fileName === '' || $fileName === '/') {
                $fileName = 'cv-file';
            }

            return [
                'content' => $response->getContent(),
                'mimeType' => $mimeType,
                'fileName' => $fileName,
            ];
        } catch (TransportExceptionInterface|\RuntimeException $e) {
            $this->logger->warning('Supabase download failed', [
                'url' => $url,
                'authenticated' => $authenticated,
                'error' => $e->getMessage(),
            ]);

            throw new \RuntimeException('Failed to download file from remote storage.');
        }
    }

    private function extractObjectPathFromPublicUrl(string $url): ?string
    {
        $base = rtrim($this->supabaseUrl, '/');
        $publicPrefix = $base . '/storage/v1/object/public/' . rawurlencode($this->supabaseBucket) . '/';
        if (!str_starts_with($url, $publicPrefix)) {
            return null;
        }

        $encodedPath = substr($url, strlen($publicPrefix));
        if ($encodedPath === false || $encodedPath === '') {
            return null;
        }

        return rawurldecode($encodedPath);
    }
}
